import type { Metadata } from "next";
import { Noto_Color_Emoji, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import RightSidebar from "@/components/RightSidebar";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});
const notoColorEmoji = Noto_Color_Emoji({
  subsets: ["emoji"],
  variable: "--font-emoji",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} ${notoColorEmoji.variable} antialiased`}
      >
        <NavigationBar />
        {/* 三列布局 */}
        <div className="grid grid-cols-[22rem_1fr_22rem] w-full h-[calc(100vh-4rem)]">
          {/* 左侧列 */}
          <div className="bg-gray-50 p-4">{/* 可放左侧工具栏或留空 */}</div>

          {/* 中间列 */}
          <main className="overflow-auto p-4 flex justify-center">
            <div className="w-full max-w-xl">{children}</div>
          </main>

          {/* 右侧列 */}
          <div className="p-4">
            <RightSidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
