import type { Metadata } from "next";
import { Noto_Color_Emoji, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});
const notoColorEmoji = Noto_Color_Emoji({
  subsets: ["emoji"],
  variable: "--font-emoji",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} ${notoColorEmoji.variable} antialiased`}
      >
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
